name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: |
        Home Assistant Version, Editor Version, Browser, etc.
      placeholder: |
        - Home Assistant: 2024.x
        - Editor Version: 1.1.0
        - Browser: Chrome/Safari/Firefox
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide logs from the add-on if applicable.
