blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/saihgupr/HomeAssistantEditor/discussions
    about: Please check existing discussions before opening an issue.
